buildscript {
    ext.kotlin_version = '2.1.0'
    repositories {
        google()
        mavenCentral()
    }

    dependencies {
        classpath "org.jetbrains.kotlin:kotlin-gradle-plugin:$kotlin_version"
    }
}

allprojects {
    repositories {
        google()
        mavenCentral()
    }
}

rootProject.buildDir = '../build'
subprojects {
    project.buildDir = "${rootProject.buildDir}/${project.name}"
}

allprojects {
    plugins.withId("com.android.library") {
        android {
            if (namespace == null) {
                namespace project.group
            }
            buildFeatures {
                buildConfig true
            }
            compileOptions {
                sourceCompatibility JavaVersion.VERSION_17
                targetCompatibility JavaVersion.VERSION_17
            }
        }
        if (project.plugins.hasPlugin("kotlin-android") || project.plugins.hasPlugin("kotlin")) {
            android {
                kotlinOptions {
                    jvmTarget = '17'
                }
            }
        }
    }
    plugins.withId("com.android.application") {
        android {
            if (namespace == null) {
                namespace project.group
            }
            compileOptions {
                sourceCompatibility JavaVersion.VERSION_17
                targetCompatibility JavaVersion.VERSION_17
            }
        }
        if (project.plugins.hasPlugin("kotlin-android") || project.plugins.hasPlugin("kotlin")) {
            android {
                kotlinOptions {
                    jvmTarget = '17'
                }
            }
        }
    }
}

subprojects {
    project.evaluationDependsOn(':app')
}

tasks.register("clean", Delete) {
    delete rootProject.buildDir
}
