// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCbIMqynbA-AysrdTwJ4fzYtp8-Zbafd-k',
    appId: '1:328990507309:web:1e41ab35cd4d8f279c13a4',
    messagingSenderId: '328990507309',
    projectId: 'call-finder-7afd6',
    authDomain: 'call-finder-7afd6.firebaseapp.com',
    storageBucket: 'call-finder-7afd6.firebasestorage.app',
    measurementId: 'G-D5B5C42LGQ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCC2X4KYb8FY-PJn1GsZDsWb-BmF4exRlk',
    appId: '1:328990507309:android:62861c9aa7b7c41b9c13a4',
    messagingSenderId: '328990507309',
    projectId: 'call-finder-7afd6',
    storageBucket: 'call-finder-7afd6.firebasestorage.app',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCbIMqynbA-AysrdTwJ4fzYtp8-Zbafd-k',
    appId: '1:328990507309:web:3870eff37cc8b2129c13a4',
    messagingSenderId: '328990507309',
    projectId: 'call-finder-7afd6',
    authDomain: 'call-finder-7afd6.firebaseapp.com',
    storageBucket: 'call-finder-7afd6.firebasestorage.app',
    measurementId: 'G-81RJ6CB9P1',
  );
}
